apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: babblebox-transcription-service
  name: babblebox-transcription-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: babblebox-transcription-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/babblebox-transcription-service-default: "true"
        io.kompose.service: babblebox-transcription-service
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
        - image: 767397752164.dkr.ecr.us-east-1.amazonaws.com/babblebox_transcription_service
          name: babblebox-transcription-service
          env:
            - name: BABBLEBOX_TRANSCRIPTION_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: BABBLEBOX_TRANSCRIPTION_API_KEY
                  name: djangoc
            - name: BABBLEBOX_URL
              valueFrom:
                configMapKeyRef:
                  key: BABBLEBOX_URL
                  name: djangoc
            - name: PULSAR_URL
              valueFrom:
                configMapKeyRef:
                  key: PULSAR_URL
                  name: djangoc
          volumeMounts:
            - mountPath: /tmp/whisper
              name: whisper-models
      restartPolicy: Always
      volumes:
        - name: whisper-models
          persistentVolumeClaim:
            claimName: whisper-models
